/** Declaration file generated by dts-gen */

export = mongoose_integer;

declare function mongoose_integer(schema: any, options: any): any;

declare namespace mongoose_integer {
    const prototype: {
    };

}
